# fly.toml app configuration file generated for gotquestions-web-backend on 2025-04-10T14:36:24-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gotquestions-web-backend'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
